CREATE USER C##ADMIN IDENTIFIED BY admin123;
-- เข้า PDB XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

-- ไม่ต้อง CREATE USER ซ้ำ เพราะ C##ADMIN ถูกสร้างแล้วที่ CDB$ROOT
-- แก้เป็น GRANT สิทธิ์ใน PDB แทน
GRANT CREATE SESSION TO C##ADMIN;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO C##ADMIN;
ALTER USER C##ADMIN QUOTA UNLIMITED ON USERS;

-- เปลี่ยนรหัส SYSTEM (อันนี้เลือกได้ว่าจะใช้หรือไม่)
-- ALTER USER SYSTEM IDENTIFIED BY "newPassword123";

--
-- CREATE TABLE C##SERVICE.BUCKETS_STORAGE
-- (
--     BK_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
--     BK_BUCKET_NAME VARCHAR2(50) NOT NULL,
--     BK_PATH_BUCKET VARCHAR2(1024) NOT NULL,
--     BK_METADATA_BUCKET CLOB,
--     BK_MIME_TYPE VARCHAR2(50) NOT NULL,
--     BK_CREATED_BY VARCHAR2(100) NOT NULL,
--     BK_CREATED_TIME TIMESTAMP NOT NULL,
--     CONSTRAINT PK_BK_ID PRIMARY KEY (BK_ID)
-- );
--
-- CREATE TABLE C##SERVICE.FILES_STORAGE
-- (
--     FS_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
--     BK_ID NUMBER NOT NULL,
--     FS_FILE_NAME VARCHAR2(50) NOT NULL,
--     FS_PATH_FILE VARCHAR2(1024) NOT NULL,
--     FS_METADATA_FILE CLOB,
--     FS_MIME_TYPE VARCHAR2(50) NOT NULL,
--     FS_CREATED_BY VARCHAR2(100) NOT NULL,
--     FS_CREATED_TIME TIMESTAMP NOT NULL,
--     CONSTRAINT PK_FS_ID PRIMARY KEY (FS_ID),
--     CONSTRAINT FK_FILES_BUCKET FOREIGN KEY (BK_ID) REFERENCES C##SERVICE.BUCKETS_STORAGE(BK_ID)
-- );
--
--
-- GRANT SELECT, INSERT, UPDATE, DELETE ON C##SERVICE.FILES_STORAGE TO C##SERVICE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON C##SERVICE.BUCKETS_STORAGE TO C##SERVICE;
--
-- -- Set Auto Commit Off
SET AUTOCOMMIT OFF;

-- @/tmp/script_craeate_user.sql
