package com.int371.eventhub.service;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.int371.eventhub.dto.AdminCreateUserRequestDto;
import com.int371.eventhub.dto.AdminCreateUserResponseDto;
import com.int371.eventhub.dto.AdminUpdateUserRequestDto;
import com.int371.eventhub.entity.User;
import com.int371.eventhub.entity.UserRole;
import com.int371.eventhub.entity.UserStatus;
import com.int371.eventhub.exception.ResourceNotFoundException;
import com.int371.eventhub.repository.CityRepository;
import com.int371.eventhub.repository.CountryRepository;
import com.int371.eventhub.repository.JobRepository;
import com.int371.eventhub.repository.UserRepository;

@Service
public class AdminService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private AuthService authService;

    @Autowired
    private JobRepository jobRepository;

    @Autowired
    private CountryRepository countryRepository;

    @Autowired
    private CityRepository cityRepository;

    public AdminCreateUserResponseDto createUserByAdmin(AdminCreateUserRequestDto request, String adminEmail) {
        User admin = userRepository.findByEmail(adminEmail)
                .orElseThrow(() -> new ResourceNotFoundException("Admin not found"));
        String adminName = admin.getFirstName() + " " + admin.getLastName();

        if (userRepository.existsByEmailIgnoreCase(request.getEmail())) {
            throw new IllegalArgumentException("Error: Email has been registered!");
        }

        boolean isAutoGeneratedPassword = false;
        String rawPassword = request.getPassword();

        if (rawPassword == null || rawPassword.trim().isEmpty()) {
            rawPassword = authService.generateRandomPassword();
            isAutoGeneratedPassword = true;
        }

        String encodedPassword = passwordEncoder.encode(rawPassword);

        User user = new User();
        user.setEmail(request.getEmail());
        user.setFirstName(request.getFirstName());
        user.setLastName(request.getLastName());
        user.setPassword(encodedPassword);
        user.setStatus(UserStatus.ACTIVE);

        user.setRole(UserRole.GENERAL_USER);
        user.setGender(request.getGender());
        user.setDateOfBirth(request.getDateOfBirth());

        User savedUser = userRepository.save(user);

        // Send welcome email (rawPassword is passed if it was auto generated)
        authService.sendWelcomeEmailAfterRegistration(savedUser, isAutoGeneratedPassword ? rawPassword : null,
                isAutoGeneratedPassword);

        return new AdminCreateUserResponseDto(
                savedUser.getId(),
                savedUser.getEmail(),
                savedUser.getFirstName(),
                savedUser.getLastName(),
                savedUser.getRole(),
                savedUser.getCreatedAt(),
                adminName);
    }

    @Transactional
    public Map<String, Object> updateUser(Integer userId, AdminUpdateUserRequestDto request) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + userId));

        if (request.getFirstName() != null)
            user.setFirstName(request.getFirstName());
        if (request.getLastName() != null)
            user.setLastName(request.getLastName());
        if (request.getEmail() != null) {
            if (!user.getEmail().equalsIgnoreCase(request.getEmail())
                    && userRepository.existsByEmailIgnoreCase(request.getEmail())) {
                throw new IllegalArgumentException("Email already in use by another user.");
            }
            user.setEmail(request.getEmail());
        }
        if (request.getPassword() != null && !request.getPassword().trim().isEmpty()) {
            user.setPassword(passwordEncoder.encode(request.getPassword()));
        }
        if (request.getRole() != null)
            user.setRole(request.getRole());
        if (request.getPhone() != null)
            user.setPhone(request.getPhone());
        if (request.getDateOfBirth() != null)
            user.setDateOfBirth(request.getDateOfBirth());
        if (request.getGender() != null)
            user.setGender(request.getGender());
        if (request.getAddress() != null)
            user.setAddress(request.getAddress());
        if (request.getPostCode() != null)
            user.setPostCode(request.getPostCode());
        if (request.getImgPath() != null)
            user.setImgPath(request.getImgPath());
        if (request.getStatus() != null)
            user.setStatus(request.getStatus());

        if (request.getJobId() != null) {
            user.setJob(jobRepository.findById(request.getJobId())
                    .orElseThrow(() -> new ResourceNotFoundException("Job not found with id: " + request.getJobId())));
        }
        if (request.getCountryId() != null) {
            user.setCountry(countryRepository.findById(request.getCountryId())
                    .orElseThrow(() -> new ResourceNotFoundException(
                            "Country not found with id: " + request.getCountryId())));
        }
        if (request.getCityId() != null) {
            user.setCity(cityRepository.findById(request.getCityId())
                    .orElseThrow(
                            () -> new ResourceNotFoundException("City not found with id: " + request.getCityId())));
        }

        User savedUser = userRepository.save(user);

        return Map.of(
                "id", savedUser.getId(),
                "email", savedUser.getEmail(),
                "firstName", savedUser.getFirstName(),
                "lastName", savedUser.getLastName(),
                "role", savedUser.getRole(),
                "status", savedUser.getStatus());
    }

    @Transactional
    public void deleteUser(Integer userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + userId));
        userRepository.delete(user);
    }
}
