package com.int371.eventhub.service;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.int371.eventhub.dto.AdminCreateUserRequestDto;
import com.int371.eventhub.dto.AdminCreateUserResponseDto;
import com.int371.eventhub.dto.AdminUpdateUserRequestDto;
import com.int371.eventhub.entity.User;
import com.int371.eventhub.entity.UserRole;
import com.int371.eventhub.entity.UserStatus;
import com.int371.eventhub.exception.ResourceNotFoundException;
import com.int371.eventhub.repository.CityRepository;
import com.int371.eventhub.repository.CountryRepository;
import com.int371.eventhub.repository.JobRepository;
import com.int371.eventhub.repository.MemberEventRepository;
import com.int371.eventhub.repository.UserRepository;
import com.int371.eventhub.repository.EventRepository;
import com.int371.eventhub.entity.Event;
import com.int371.eventhub.entity.MemberEvent;
import com.int371.eventhub.entity.MemberEventRole;
import com.int371.eventhub.dto.AdminAddUserToEventRequestDto;
import com.int371.eventhub.repository.ResponseAnswerRepository;
import com.int371.eventhub.repository.SuggestionsAnalysisRepository;
import com.int371.eventhub.repository.UserRewardRepository;

@Service
public class AdminService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private AuthService authService;

    @Autowired
    private JobRepository jobRepository;

    @Autowired
    private CountryRepository countryRepository;

    @Autowired
    private CityRepository cityRepository;

    @Autowired
    private MemberEventRepository memberEventRepository;

    @Autowired
    private EventRepository eventRepository;

    @Autowired
    private ResponseAnswerRepository responseAnswerRepository;

    @Autowired
    private SuggestionsAnalysisRepository suggestionsAnalysisRepository;

    @Autowired
    private UserRewardRepository userRewardRepository;

    public AdminCreateUserResponseDto createUserByAdmin(AdminCreateUserRequestDto request, String adminEmail) {
        User admin = userRepository.findByEmail(adminEmail)
                .orElseThrow(() -> new ResourceNotFoundException("Admin not found"));
        String adminName = admin.getFirstName() + " " + admin.getLastName();

        if (userRepository.existsByEmailIgnoreCase(request.getEmail())) {
            throw new IllegalArgumentException("Error: Email has been registered!");
        }

        boolean isAutoGeneratedPassword = false;
        String rawPassword = request.getPassword();

        if (rawPassword == null || rawPassword.trim().isEmpty()) {
            rawPassword = authService.generateRandomPassword();
            isAutoGeneratedPassword = true;
        }

        String encodedPassword = passwordEncoder.encode(rawPassword);

        User user = new User();
        user.setEmail(request.getEmail());
        user.setFirstName(request.getFirstName());
        user.setLastName(request.getLastName());
        user.setPassword(encodedPassword);
        user.setStatus(UserStatus.ACTIVE);

        user.setRole(UserRole.GENERAL_USER);
        user.setGender(request.getGender());
        user.setDateOfBirth(request.getDateOfBirth());

        User savedUser = userRepository.save(user);

        // Send welcome email (rawPassword is passed if it was auto generated)
        authService.sendWelcomeEmailAfterRegistration(savedUser, isAutoGeneratedPassword ? rawPassword : null,
                isAutoGeneratedPassword);

        return new AdminCreateUserResponseDto(
                savedUser.getId(),
                savedUser.getEmail(),
                savedUser.getFirstName(),
                savedUser.getLastName(),
                savedUser.getRole(),
                savedUser.getCreatedAt(),
                adminName);
    }

    @Transactional
    public Map<String, Object> updateUser(Integer userId, AdminUpdateUserRequestDto request) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + userId));

        if (request.getFirstName() != null)
            user.setFirstName(request.getFirstName());
        if (request.getLastName() != null)
            user.setLastName(request.getLastName());
        if (request.getEmail() != null) {
            if (!user.getEmail().equalsIgnoreCase(request.getEmail())
                    && userRepository.existsByEmailIgnoreCase(request.getEmail())) {
                throw new IllegalArgumentException("Email already in use by another user.");
            }
            user.setEmail(request.getEmail());
        }
        if (request.getPassword() != null && !request.getPassword().trim().isEmpty()) {
            user.setPassword(passwordEncoder.encode(request.getPassword()));
        }
        if (request.getRole() != null)
            user.setRole(request.getRole());
        if (request.getPhone() != null)
            user.setPhone(request.getPhone());
        if (request.getDateOfBirth() != null)
            user.setDateOfBirth(request.getDateOfBirth());
        if (request.getGender() != null)
            user.setGender(request.getGender());
        if (request.getAddress() != null)
            user.setAddress(request.getAddress());
        if (request.getPostCode() != null)
            user.setPostCode(request.getPostCode());
        if (request.getImgPath() != null)
            user.setImgPath(request.getImgPath());
        if (request.getStatus() != null)
            user.setStatus(request.getStatus());

        if (request.getJobId() != null) {
            user.setJob(jobRepository.findById(request.getJobId())
                    .orElseThrow(() -> new ResourceNotFoundException("Job not found with id: " + request.getJobId())));
        }
        if (request.getCountryId() != null) {
            user.setCountry(countryRepository.findById(request.getCountryId())
                    .orElseThrow(() -> new ResourceNotFoundException(
                            "Country not found with id: " + request.getCountryId())));
        }
        if (request.getCityId() != null) {
            user.setCity(cityRepository.findById(request.getCityId())
                    .orElseThrow(
                            () -> new ResourceNotFoundException("City not found with id: " + request.getCityId())));
        }

        User savedUser = userRepository.save(user);

        return Map.of(
                "id", savedUser.getId(),
                "email", savedUser.getEmail(),
                "firstName", savedUser.getFirstName(),
                "lastName", savedUser.getLastName(),
                "role", savedUser.getRole(),
                "status", savedUser.getStatus());
    }

    // @Transactional
    // public void deleteUser(Integer userId) {
    // User user = userRepository.findById(userId)
    // .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " +
    // userId));
    // userRepository.delete(user);
    // }

    @Transactional
    public void deleteUser(Integer userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + userId));

        List<MemberEvent> userEvents = memberEventRepository.findAllByUserId(userId);
        for (MemberEvent me : userEvents) {
            // ใน loop for (MemberEvent me : userEvents)
            Integer meId = me.getId();

            // 1. ลบตารางวิเคราะห์ (ต้องเรียกผ่าน suggestionsAnalysisRepository)
            suggestionsAnalysisRepository.deleteByMemberEventId(meId);

            // 2. ลบคำตอบ (เรียกผ่าน responseAnswerRepository และใช้ชื่อ Method ให้ถูก)
            responseAnswerRepository.deleteByMemberEventId(meId);
        }

        // 2. ลบความสัมพันธ์ใน UserEvents ทั้งหมดของผู้ใช้
        memberEventRepository.deleteByUserId(userId);

        // 3. ลบข้อมูลการแลกของรางวัล (UserRewards)
        userRewardRepository.deleteByUserId(userId);

        // 4. กรณีที่ User คนนี้เป็นคนสร้าง Event (Created By)
        // คุณต้องเลือกว่าจะลบ Event นั้นทิ้ง หรือเปลี่ยนคนสร้าง (แนะนำให้ลบหากต้องการลบ
        // User จริงๆ)
        // eventRepository.deleteByCreatedBy(userId);

        // 5. ลบข้อมูล User เป็นลำดับสุดท้าย
        userRepository.delete(user);
    }

    @Transactional
    public Map<String, Object> addUserToEvent(Integer eventId, AdminAddUserToEventRequestDto request) {
        Event event = eventRepository.findById(eventId)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + eventId));

        User user = userRepository.findById(request.getUserId())
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + request.getUserId()));

        if (memberEventRepository.existsByUserIdAndEventId(user.getId(), event.getId())) {
            throw new IllegalArgumentException("User is already registered for this event.");
        }

        MemberEvent memberEvent = new MemberEvent(user, event, MemberEventRole.VISITOR);
        memberEventRepository.save(memberEvent);

        return Map.of(
                "eventId", event.getId(),
                "userId", user.getId(),
                "role", memberEvent.getEventRole(),
                "status", memberEvent.getStatus());
    }

    @Transactional
    public void removeUserFromEvent(Integer eventId, Integer userId) {
        MemberEvent memberEvent = memberEventRepository.findByUserIdAndEventId(userId, eventId)
                .orElseThrow(() -> new ResourceNotFoundException("User is not registered in this event."));

        Integer memberEventId = memberEvent.getId();

        suggestionsAnalysisRepository.deleteByMemberEventId(memberEventId);

        responseAnswerRepository.deleteByMemberEventId(memberEventId);

        memberEventRepository.delete(memberEvent);
    }

    public List<Map<String, Object>> getAllUsers() {
        return userRepository.findAll().stream().map(user -> Map.<String, Object>of(
                "id", user.getId(),
                "email", user.getEmail(),
                "firstName", user.getFirstName(),
                "lastName", user.getLastName(),
                "role", user.getRole(),
                "status", user.getStatus())).collect(Collectors.toList());
    }

    @Transactional
    public Map<String, Object> updateMemberEventRole(Integer eventId, Integer userId, MemberEventRole newRole) {
        MemberEvent memberEvent = memberEventRepository.findByUserIdAndEventId(userId, eventId)
                .orElseThrow(() -> new ResourceNotFoundException("Member not found in this event."));

        memberEvent.setEventRole(newRole);
        memberEventRepository.save(memberEvent);

        return Map.of(
                "eventId", eventId,
                "userId", userId,
                "role", newRole);
    }

    public List<Map<String, Object>> getAllEventMembers() {
        List<MemberEvent> members = memberEventRepository.findAll();

        return members.stream().map(member -> {
            User user = member.getUser();
            Event event = member.getEvent();
            return Map.<String, Object>of(
                    "eventId", event.getId(),
                    "eventName", event.getEventName(),
                    "userId", user.getId(),
                    "email", user.getEmail(),
                    "firstName", user.getFirstName(),
                    "lastName", user.getLastName(),
                    "eventRole", member.getEventRole(),
                    "checkInStatus", member.getStatus());
        }).collect(Collectors.toList());
    }

    public List<Map<String, Object>> getAllUsersInEvent(Integer eventId) {
        if (!eventRepository.existsById(eventId)) {
            throw new ResourceNotFoundException("Event not found with id: " + eventId);
        }

        List<MemberEvent> members = memberEventRepository.findByEventId(eventId);

        return members.stream().map(member -> {
            User user = member.getUser();
            return Map.<String, Object>of(
                    "userId", user.getId(),
                    "email", user.getEmail(),
                    "firstName", user.getFirstName(),
                    "lastName", user.getLastName(),
                    "eventRole", member.getEventRole(),
                    "checkInStatus", member.getStatus());
        }).collect(Collectors.toList());
    }

    public List<Event> getAllEventsForAdmin() {
        return eventRepository.findAll();
    }

    @Transactional
    public Map<String, Object> changeEventStatus(Integer eventId, com.int371.eventhub.entity.EventStatus status) {
        Event event = eventRepository.findById(eventId)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + eventId));

        event.setStatus(status);
        eventRepository.save(event);

        return Map.of(
                "eventId", event.getId(),
                "status", event.getStatus());
    }
}